{
    "version": 2.6,
    "type": "FlowCanvas.FlowScript",
    "name": "FlowScript",
    "nodes": [
        {
            "_inputPortValues": {

            },
            "_nodeColor": {
                "r": 1.0,
                "g": 0.3607843,
                "b": 0.3607843,
                "a": 1.0
            },
            "_position": {
                "x": 5507.0,
                "y": 5241.0
            },
            "$type": "FlowCanvas.Nodes.ConstructionEvent"
        }
    ],
    "connections": [],
    "localBlackboard": {
        "_name": "Local Blackboard",
        "_variables": {

        }
    }
}